### login
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "{{adminEmail}}",
    "password": "{{adminPassword}}"
}

> {%
    client.test('Login user', function() {
        client.assert(response.status === 200, "Login user OK");
        client.global.set('accessToken', response.body.accessToken)
    });
%}

### getCalendar
GET {{host}}/training
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### getTrainingList

GET {{host}}/catalogs/training-list
Authorization: Bearer {{accessToken}}
